name: Linux RDP + Tailscale
on:
  workflow_dispatch:
jobs:
  rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup Tailscale
        env:
          TS_KEY: ${{ secrets.TS_AUTHKEY }}
        run: |
          echo "Checking key format..."
          echo "Prefix: ${TS_KEY:0:12}"
          if [ -z "$TS_KEY" ]; then echo "❌ Secret فاضي"; exit 1; fi
          if [[ "$TS_KEY" != tskey-auth-* ]]; then echo "❌ ده مش Auth Key - لازم يبدأ بـ tskey-auth-"; exit 1; fi
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="$TS_KEY" --hostname=gh-rdp-$(date +%s)
          tailscale ip -4
      - name: Install XRDP
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies dbus-x11 xrdp xorgxrdp
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          sudo bash -c 'cat > /etc/xrdp/startwm.sh <<EOF
          #!/bin/sh
          if [ -r /etc/default/locale ]; then . /etc/default/locale; export LANG LANGUAGE; fi
          unset DBUS_SESSION_BUS_ADDRESS
          unset XDG_RUNTIME_DIR
          startxfce4
          EOF'
          sudo chmod +x /etc/xrdp/startwm.sh
          sudo useradd -m rdpuser || true
          echo "rdpuser:123456" | sudo chpasswd
          sudo adduser xrdp ssl-cert
          echo "startxfce4" | sudo tee /home/rdpuser/.xsession > /dev/null
          echo "startxfce4" > ~/.xsession
          sudo chown rdpuser:rdpuser /home/rdpuser/.xsession
          sudo service xrdp restart
      - name: Keep Alive
        run: |
          echo "User: rdpuser Pass: 123456 IP: $(tailscale ip -4)"
          while true; do sleep 60; done
